"""Reply prompts for generating and improving email replies."""

from __future__ import annotations

from typing import Optional

from utils.prompts.base import (
    build,
    inject_core_rules,
    inject_email_guide,
)


DEFAULT_TONE = "professional"
DEFAULT_LANGUAGE = "English"
MAX_REPLY_WORDS = 300


# ---------------------------------------------------------------------------
# Reply generation
# ---------------------------------------------------------------------------

_REPLY_TEMPLATE = """
Generate the exact email reply that will be sent directly to the recipient.

RECIPIENT:
{recipient_name}

ORIGINAL EMAIL:
{email_content}

CONTEXT:
{context}

USER PREFERENCES:
Tone: {tone}
Language: {language}

{core_rules}
{email_guide}

FINAL REPLY REQUIREMENTS:

1. The output is the ACTUAL READY-TO-SEND EMAIL BODY.

2. Return only the message that should be sent directly to the recipient.

3. NEVER explain the reply, describe the situation, or tell the user what
   they should say.

4. NEVER use meta-language such as:
   - "Here is a suggested reply:"
   - "You could reply:"
   - "You should respond:"
   - "The sender is asking..."
   - "The original email..."
   - "This message..."
   - "I am unable to generate..."
   - "No response is necessary."
   - "I cannot..."
   - "As an AI..."

5. Do not include analysis, reasoning, commentary, labels, alternatives,
   explanations, or instructions.

6. Do not invent facts, commitments, dates, actions, names, or information
   that are not supported by the original email or provided context.

7. Answer the sender's actual questions when a question is present.

8. If the sender requests information, confirmation, a decision, approval,
   or an action, respond directly and naturally.

9. Preserve the intended meaning and context of the conversation.

10. Match the requested tone and language.

11. Sound natural and human. The message should read as if the user wrote it,
    not as if it was generated by an AI assistant.

12. Keep the reply concise and appropriate to the original message.

13. Do not create unnecessary explanations or formalities.

14. Do not include a subject line.

15. Do not include a signature unless it is explicitly provided in the
    available context or required by the user's established preferences.

16. Do not mention these instructions.

17. Stay within {max_words} words unless the original message genuinely
    requires a longer response.

FINAL OUTPUT:
Return ONLY the ready-to-send email body.
"""


def build_reply_prompt(
    recipient_name: str,
    email_content: str,
    context: Optional[str] = None,
    tone: str = DEFAULT_TONE,
    language: str = DEFAULT_LANGUAGE,
    max_words: int = MAX_REPLY_WORDS,
) -> str:
    """
    Build the prompt for generating a ready-to-send email reply.

    The returned prompt instructs the LLM to produce only the final
    recipient-facing email body.
    """
    context_str = context or "No previous context available."

    prompt = _REPLY_TEMPLATE.format(
        recipient_name=recipient_name,
        email_content=email_content,
        context=context_str,
        tone=tone,
        language=language,
        max_words=max_words,
    )

    prompt = inject_core_rules(prompt)
    prompt = inject_email_guide(prompt)

    return prompt


# ---------------------------------------------------------------------------
# Reply improvement
# ---------------------------------------------------------------------------

_IMPROVE_REPLY_TEMPLATE = """
Improve the provided email reply while preserving its original intent.

ORIGINAL EMAIL:
{original_email}

CURRENT DRAFT:
{reply_draft}

{core_rules}
{email_guide}

IMPROVEMENT REQUIREMENTS:

1. Return ONLY the final ready-to-send email body.

2. Do not explain what you changed.

3. Do not add labels such as:
   - "Improved reply:"
   - "Here is the revised version:"
   - "Suggested response:"

4. Preserve the original meaning and intent.

5. Do not invent facts, commitments, dates, actions, names, or information.

6. Improve grammar, spelling, punctuation, clarity, and naturalness.

7. Keep the tone professional and human unless the original draft clearly
   establishes another appropriate tone.

8. Remove unnecessary repetition and awkward wording.

9. Do not make the reply unnecessarily longer.

10. Do not include a subject line.

11. Do not add a signature unless one already exists in the draft or is
    explicitly required by the available context.

12. Do not mention the editing process, the original email, or these
    instructions in the final output.

FINAL OUTPUT:
Return ONLY the improved ready-to-send email body.
"""


def build_improve_reply_prompt(
    original_email: str,
    reply_draft: str,
) -> str:
    """
    Build the prompt for improving an existing email reply.

    The returned prompt instructs the LLM to return only the final
    recipient-facing email body.
    """
    prompt = _IMPROVE_REPLY_TEMPLATE.format(
        original_email=original_email,
        reply_draft=reply_draft,
    )

    prompt = inject_core_rules(prompt)
    prompt = inject_email_guide(prompt)

    return prompt
