// This file is auto-generated by scripts/generate_assets.py. Do not edit directly.
export const LEGAL_CONTENT = {
  privacy: {
    title: 'Privacy Policy for SidekickAI',
    effectiveDate: 'August 3, 2026',
    html: `<p>SidekickAI ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our web application located at https://sidekickai.onrender.com (the "Service").</p>
<p>By accessing or using our Service, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with any terms of this policy, please do not use the Service.</p>
<hr />
<h2>1. Information Collection</h2>
<p>We collect several types of information to provide and improve our Service:</p>
<h3>A. Information You Provide Directly</h3>
<ul>
  <li><strong>Account Information:</strong> When you register for an account, we collect your full name, email address, password (stored securely using industry-standard hashing algorithms), and user preferences.</li>
  <li><strong>Communications:</strong> If you contact us directly, we may collect your email address, message contents, and any attachments you send.</li>
</ul>
<h3>B. Third-Party Integrations & OAuth Authorized Data</h3>
<p>To deliver our AI assistant functionalities, SidekickAI connects with external platforms via OAuth protocol. We access only the permissions you explicitly grant during authentication:</p>
<ul>
  <li><strong>Google Workspace APIs (Gmail & Calendar):</strong></li>
  <ul>
    <li><strong>Gmail Scopes:</strong> We access Gmail messages (read, modify, send, and compose permissions) to pull email history, synthesize summaries, detect priority threads, and generate draft responses.</li>
    <li><strong>Google Calendar Scopes:</strong> We access calendar events (read and write permissions) to retrieve your schedule timeline, update calendar entries, and compile your daily executive briefing.</li>
    <li><strong>OAuth Tokens:</strong> We receive and securely store encrypted Google refresh and access tokens to synchronize your data in the background.</li>
  </ul>
  <li><strong>WhatsApp Cloud API:</strong></li>
  <ul>
    <li><strong>Embedded Signup flow:</strong> Integrates strictly with Meta's official WhatsApp Business Platform. We access your registered WhatsApp Business Account (WABA) ID, connected phone numbers, and customer chats.</li>
    <li><strong>Access Limitations:</strong> This integration requires a dedicated business number. It <strong>cannot</strong> connect personal WhatsApp profiles, read personal chats, or sync standard private numbers.</li>
  </ul>
</ul>
<hr />
<h2>2. How We Use Your Information</h2>
<p>We use the collected information for various purposes, including to:</p>
<ul>
  <li><strong>Operate the Service:</strong> Sync email lists, calendar schedules, and WhatsApp customer chats.</li>
  <li><strong>Generate AI Assist Capabilities:</strong> Analyze email headers and body texts using LLMs to prioritize threads, draft proposed reply templates, and build your Daily Briefing.</li>
  <li><strong>Improve & Personalize:</strong> Track application performance, resolve configuration bugs, and enhance user experience layouts.</li>
  <li><strong>Security & Authentication:</strong> Verify user accounts, secure API sessions, and maintain OAuth credential token rotations.</li>
</ul>
<hr />
<h2>3. Data Sharing & Disclosure</h2>
<p>We do not sell, trade, or rent your personal information to third parties. We may disclose data under the following circumstances:</p>
<ul>
  <li><strong>With Service Providers:</strong> We share content with verified sub-processors (such as LLM endpoint providers like OpenRouter) solely to process your prompts and draft summaries. These providers are bound by strict confidentiality obligations and do not use your data to train their public models.</li>
  <li><strong>Legal Requirements:</strong> If required by law, subpoena, or government regulation, we may disclose information to comply with valid legal processes.</li>
  <li><strong>Business Transfers:</strong> If SidekickAI undergoes a merger, acquisition, or asset sale, your personal information may be transferred. We will notify you before your data becomes subject to a different policy.</li>
</ul>
<hr />
<h2>4. Data Security</h2>
<p>We implement robust administrative, technical, and physical security measures to safeguard your credentials and data:</p>
<ul>
  <li><strong>Encryption:</strong> All OAuth credentials (tokens) are stored in our database using strong AES-256 encryption. All network communications use secure HTTPS/TLS transport protocols.</li>
  <li><strong>Access Control:</strong> System database sessions are restricted to authenticated service layers. Database engines are isolated from direct external internet access.</li>
  <li><strong>No Cache Retention for LLMs:</strong> When we send email or chat content to LLM endpoints for synthesis, the data is passed securely and is not cached or used for training.</li>
</ul>
<hr />
<h2>5. User Rights</h2>
<p>Depending on your jurisdiction (such as under GDPR or CCPA), you may have the following rights regarding your data:</p>
<ul>
  <li><strong>Access & Sync:</strong> You can view all linked data and integrations directly on the dashboard.</li>
  <li><strong>Data Rectification:</strong> You can modify your profile details and connection settings at any time in the Settings portal.</li>
  <li><strong>Data Erasure (Right to be Forgotten):</strong> You can delete your account or disconnect specific integrations. Disconnecting a service instantly deletes the corresponding OAuth credentials, synced messages, and cached indexes from our database.</li>
  <li><strong>Contact:</strong> To request complete account erasure or export your details, email us at humammoin09@gmail.com.</li>
</ul>
<hr />
<h2>6. Cookies & Tracking Technologies</h2>
<p>We use basic HTTP cookies and local storage tokens to manage user sessions and login authentication states:</p>
<ul>
  <li><strong>Auth Cookies:</strong> Secure JWT cookie tokens are stored in your browser to maintain your session state.</li>
  <li><strong>Preferences Storage:</strong> Local storage is used to save theme states and interface layouts.</li>
  <li><strong>No Third-Party Ad Trackers:</strong> We do not host third-party advertisement trackers, analytics beacons, or retargeting scripts.</li>
</ul>
<hr />
<h2>7. Changes to This Privacy Policy</h2>
<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Effective Date" at the top. We recommend checking this page periodically for updates.</p>
<hr />
<h2>8. Contact Us</h2>
<p>If you have any questions or suggestions about this Privacy Policy, please contact us:</p>
<ul>
  <li><strong>By Email:</strong> humammoin09@gmail.com</li>
  <li><strong>Official Website:</strong> https://sidekickai.onrender.com</li>
</ul>`
  },
  terms: {
    title: 'Terms of Service for SidekickAI',
    effectiveDate: 'August 3, 2026',
    html: `<p>Welcome to SidekickAI!</p>
<p>These Terms of Service ("Terms") govern your access to and use of the SidekickAI website and web application located at https://sidekickai.onrender.com (the "Service" or "Platform").</p>
<p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access or use the Service.</p>
<hr />
<h2>1. Description of Service</h2>
<p>SidekickAI is an AI-powered executive assistant platform designed to assist users in prioritizing communications, drafting replies, and coordinating schedules across connected systems (including Gmail, Google Calendar, and WhatsApp Business).</p>
<hr />
<h2>2. Account Registration & Security</h2>
<p>To use the Service, you must create a user profile. You agree to:</p>
<ul>
  <li>Provide accurate, current, and complete registration information.</li>
  <li>Maintain the confidentiality of your password and account credentials.</li>
  <li>Accept responsibility for all actions that occur under your account session.</li>
  <li>Immediately notify us of any unauthorized use or security breaches by contacting humammoin09@gmail.com.</li>
</ul>
<hr />
<h2>3. Third-Party Integrations & Scope Boundaries</h2>
<p>SidekickAI utilizes API access to sync and write data on your behalf. By authorizing integrations, you acknowledge their specific functional scopes:</p>
<ul>
  <li><strong>Google OAuth:</strong> SidekickAI is granted read/write permissions for Gmail messages and Calendar schedules to generate briefs, categorize priorities, and draft or send email replies.</li>
  <li><strong>Meta WhatsApp Cloud API:</strong> Serves only registered business accounts (WABA). Connection requires a business phone number; personal accounts cannot be linked.</li>
</ul>
<p>We are not liable for any service interruptions, API deprecations, or policy changes implemented by Google, Meta, or other third-party provider platforms.</p>
<hr />
<h2>4. User Responsibilities & Acceptable Use</h2>
<p>You agree that you will not use the Service to:</p>
<ul>
  <li>Violate any applicable local, state, national, or international laws.</li>
  <li>Distribute unsolicited promotional materials, spam, or bulk marketing messages.</li>
  <li>Inject malicious code, trojans, worms, or attempt unauthorized entry into the database.</li>
  <li>Impersonate any entity or forge email/message headers.</li>
  <li>Interfere with or disrupt the servers or networks connected to the Service.</li>
</ul>
<hr />
<h2>5. Intellectual Property Rights</h2>
<p>Unless otherwise stated, SidekickAI and/or its licensors own all intellectual property rights for the design, code, graphics, branding, and workflows on the Platform. All rights are reserved. You are granted a limited, non-exclusive, non-transferable license to access the interface for personal or standard business assistant operations.</p>
<hr />
<h2>6. Disclaimer of Warranties</h2>
<p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. SidekickAI makes no representations or warranties of any kind, express or implied, as to the operation of the Service, the accuracy of AI-generated email/chat drafts, or the completeness of the briefings.</p>
<p>We do not warrant that:</p>
<ul>
  <li>The Service will function uninterrupted, secure, or available at any specific time or location.</li>
  <li>Any errors or bugs in the software will be corrected immediately.</li>
  <li>The AI-generated drafts are free of errors or fit for legal, commercial, or confidential correspondence without human review. <strong>Users must review all draft replies before approving and sending.</strong></li>
</ul>
<hr />
<h2>7. Limitation of Liability</h2>
<p>To the maximum extent permitted by law, in no event shall SidekickAI, nor its directors, employees, partners, agents, or suppliers, be liable for any indirect, incidental, special, consequential, or punitive damages—including loss of profits, data, goodwill, or other intangible losses—resulting from:</p>
<ul>
  <li>Your access to or use of (or inability to use) the Service.</li>
  <li>Any conduct or content of any third party on the Service.</li>
  <li>Any content obtained from the Service.</li>
  <li>Unauthorized access, use, or alteration of your transmissions or database content.</li>
</ul>
<hr />
<h2>8. Suspension & Termination</h2>
<p>We reserve the right to suspend or terminate your account and restrict access to the Service at our sole discretion, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will cease immediately, and all linked OAuth connections and data will be erased.</p>
<hr />
<h2>9. Governing Law</h2>
<p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which SidekickAI operates, without regard to its conflict of law provisions.</p>
<hr />
<h2>10. Modifications to Terms</h2>
<p>We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 15 days' notice before the new terms take effect. By continuing to access or use the Service after those revisions become effective, you agree to be bound by the updated terms.</p>
<hr />
<h2>11. Contact Us</h2>
<p>If you have any questions about these Terms, please contact us:</p>
<ul>
  <li><strong>By Email:</strong> humammoin09@gmail.com</li>
  <li><strong>Official Website:</strong> https://sidekickai.onrender.com</li>
</ul>`
  }
};
